name: SweetItemsLoader
version: '${version}'
main: top.mrxiaom.sweet.itemsadder.SweetItemsLoader
api-version: 1.13
depend: [ PlaceholderAPI ]
softdepend: [ ItemsAdder ]
authors: [ MrXiaoM ]
folia-supported: true
commands:
  sweetitemsloader:
    description: 'The main command of SweetItemsLoader'
    aliases: [ sil ]
